# -*- coding: utf-8 -*-
"""AI-task management.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ys4OfG5oOZ4JdERaPwQKqc6yNVGzBbqH
"""

!pip install transformers
!pip install nltk
!pip install pandas

import pandas as pd
from transformers import pipeline
import nltk
from datetime import datetime

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')

# Load Hugging Face model for text classification (e.g., GPT-2 or BERT)
classifier = pipeline('zero-shot-classification')

class TaskManager:
    def __init__(self):
        self.tasks = pd.DataFrame(columns=['Task', 'Category', 'Priority', 'Due Date', 'Status'])

    def add_task(self, task_text, due_date, category=None):
        # Automatically classify the category of the task if not provided
        if not category:
            category = self.classify_task(task_text)

        priority = self.get_priority(due_date)

        new_task = pd.DataFrame({
            'Task': [task_text],
            'Category': [category],
            'Priority': [priority],
            'Due Date': [due_date],
            'Status': ['Pending']
        })

        self.tasks = pd.concat([self.tasks, new_task], ignore_index=True)

    def classify_task(self, task_text):
        # Use a zero-shot classifier to classify task (e.g., work, personal, etc.)
        categories = ["work", "personal", "home", "urgent"]
        result = classifier(task_text, candidate_labels=categories)
        return result['labels'][0]

    def get_priority(self, due_date):
        # Assign priority based on due date (this is a simple heuristic)
        today = datetime.now()
        due_date = datetime.strptime(due_date, '%Y-%m-%d')
        if due_date < today:
            return 'High'
        elif (due_date - today).days <= 2:
            return 'Medium'
        else:
            return 'Low'

    def view_tasks(self):
        return self.tasks

    def update_task(self, task_index, new_status):
        self.tasks.at[task_index, 'Status'] = new_status
        return self.tasks.loc[task_index]

# Initialize TaskManager
task_manager = TaskManager()

# Add some example tasks
task_manager.add_task("Complete the project report", "2025-10-05")
task_manager.add_task("Buy groceries for the week", "2025-10-06", "personal")
task_manager.add_task("Attend team meeting at 10 AM", "2025-10-04", "work")

# View tasks
task_manager.view_tasks()

# Update a task's status
task_manager.update_task(0, 'completed')
task_manager.view_tasks()

def add_new_task():
    task_text = input("Enter your task: ")
    due_date = input("Enter due date (YYYY-MM-DD): ")
    category = input("Enter category (optional): ")

    if category.strip() == "":
        category = None

    task_manager.add_task(task_text, due_date, category)
    print("Task added successfully!\n")
    print(task_manager.view_tasks())

# Example of adding a task
add_new_task()